// <auto-generated />
using Dolly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dolly.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241109144102_DollTable")]
    partial class DollTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Dolly.Models.Dolly.DollModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dolls");
                });

            modelBuilder.Entity("Dolly.Models.Dolly.OutfitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DollId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DollId");

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("Dolly.Models.Dolly.OutfitModel", b =>
                {
                    b.HasOne("Dolly.Models.Dolly.DollModel", "Doll")
                        .WithMany("Outfits")
                        .HasForeignKey("DollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doll");
                });

            modelBuilder.Entity("Dolly.Models.Dolly.DollModel", b =>
                {
                    b.Navigation("Outfits");
                });
#pragma warning restore 612, 618
        }
    }
}
